### ISSUE TITLE
moving away from bcrypt to Argon2 for security? 

### ISSUE THREAD

**Issue by whiletrace** [codeforpdx/dwellingly_backend#4]
Its possible that we would want to move from bcrypt to argon2? for security and hashing though bcrypt is a great library. new GPUs capabilities can put an expiration date on security. An advantage of Argon2 is that it adds a memory cost along with the time cost.

**Comment by NickSchimek** [comment]
Interesting, I hadn't heard of argon2 yet. Quickly looking into it it seems there are pro's and con's, and like the other's it should be used depending on your specific use case. The two things I'd recommend is to analyze how you're going to use it, and then pick a tool that performs well while minimizing tradeoffs. For simple password hashing/storage then most the time any of the top 3 ([Scrypt](https://docs.python.org/3/library/hashlib.html#hashlib.scrypt), bcrypt, [argon2-cffi](https://github.com/hynek/argon2-cffi)) should be a good choice, I would also ensure the library being used is kept up to date, open-sourced, and used by many.

**Comment by whiletrace** [comment]
so went over this last meeting team decided to stay with bcrypt
